import "@girs/adw-1/ambient";
import "@girs/gdk-4.0/ambient";
import "@girs/gjs/ambient";
import "@girs/gjs/dom";
import "@girs/glib-2.0/ambient";
import "@girs/gnome-shell/ambient";
import "@girs/gobject-2.0/ambient";
import "@girs/gtk-4.0/ambient";
import "@girs/st-13/ambient";
