# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '32 19 * * 0'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: "stale"
        stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
        close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
        stale-pr-message: 'Stale pull request message'
        stale-pr-label: 'no-pr-activity'
        days-before-issue-stale: 21
        days-before-issue-close: 7
        days-before-pr-stale: -1
        days-before-pr-close: -1
